### ISSUE TITLE
 error: package com.facebook.flipper.android does not exist import com.facebook.flipper.android.AndroidFlipperClient;

### ISSUE THREAD

**Issue by saurabhkacholiya** [keremcubuk/react-native-boilerplate#25]
Cannot build APK in release mode 

To reproduce:- ./gradlew assembleRelease

**Comment by keremcubuk** [comment]
Hi @saurabhkacholiya,

Thank you for reporting this problem. I will work on this quickly.

**Comment by keremcubuk** [comment]
Problem fixed. @saurabhkacholiya

**Comment by vikil143** [comment]
> Hi @saurabhkacholiya,
> 
> Thank you for reporting this problem. I will work on this quickly.

what is the solution for this error I m getting this error when upgrading react-native version 61.5 to latest

**Comment by keremcubuk** [comment]
Hi @vikil143,

Did you get flipper fix? This error was caused by the wrong file directory and has been fixed. Could you share more details?

**Comment by shubhamdeol** [comment]
Hey, all
I am also having same error. please suggest some fix if available.
does previous version work?

**Comment by keremcubuk** [comment]
Could you share device information(“react-native info”) and react-native-boilerplate version?

@shubhamdeol @vikil143

**Comment by vikil143** [comment]
yes @keremcubuk  this error happen due to the wrong directory path I fixed that

**Comment by vikil143** [comment]
I have posted one more issue which is App laggy in android version 9,10 is there any solution for that

**Comment by keremcubuk** [comment]
This issue not related with this problem. Can you share your logcat and `react-native info` informations. Send me email keremcubuk@hotmail.com

**Comment by shubhamdeol** [comment]
> yes @keremcubuk this error happen due to the wrong directory path I fixed that

@keremcubuk  how you fixed this exactly can you let me know

**Comment by keremcubuk** [comment]
In this commit folder structure has been changed. Get the latest commits. Look at [this commit](https://github.com/keremcubuk/react-native-boilerplate/commit/abbfb35dc4edcd59811089d73e8d60957a9812b4)

**Comment by Osamasomy** [comment]
I face the similar kind of problem in release mode and then I delete the release folder from `./android/app/src` and after that run 
```
cd ./android
./gradlew assembleRelease
```
**and Got Success**

**Comment by daryazata** [comment]
@basemanabulsi thanks a lot, helped for me with a different project, after upgrade to RN 0.66.2 :))

**Comment by Digiraf** [comment]
i noticed the same problem but it was a an empty space syntax error in reactNativeFlipper.java.
hope it helps

**Comment by Digiraf** [comment]
I had the same error. 
Add in app/build.gradle:

dependencies {
 
    implementation platform('com.google.firebase:firebase-bom:29.0.0')
}
error gone.

**Comment by EkremBulut01** [comment]
> I faced the same error after upgrading to RN 63.3 Put `ReactNativeFlipper.java` in debug as the path `android/app/src/debug/java/com/[Your APP]/ReactNativeFlipper.java`. the same path as the init project in `https://github.com/facebook/react-native/tree/master/template/android/app/src/debug/java/com/helloworld`

Hello . Can you give more detail ?
