### ISSUE TITLE
on android device error @react-native-community_picker 

### ISSUE THREAD

**Issue by jeysinghanbu** [keremcubuk/react-native-boilerplate#30]
While running on android getting this issue

`
    FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':@react-native-community_picker'.
> Could not resolve all artifacts for configuration ':@react-native-community_picker:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.1.
     Required by:
         project :@react-native-community_picker
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve com.android.tools.build:gradle:3.2.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom'.
            > Could not GET 'https://repo.jfrog.org/artifactory/libs-release-bintray/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.pom?referrer'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org`

**Comment by keremcubuk** [comment]
Hello @jeysinghanbu, I will investigate issue. Before I need to ask kindly some questions.
- Did you clean and sync the gradle?
- What is your environment? OS and Emulator information
- What is your Android Studio version?

**Comment by jeysinghanbu** [comment]
Hi @keremcubuk, Thanks for the reply.
```
Environment:
OS: Mac Os 10.15.5 
Node: v14.5.0
Android Studio: 4.0.1
Emulator: Pixel 3_a
```

**Comment by jeysinghanbu** [comment]
After clean and sync the gradle, I'm getting new issue.

```
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:_internal_aapt2_binary'.
   > Could not resolve com.android.tools.build:aapt2:3.5.2-5435860.
```

**Comment by keremcubuk** [comment]
Hello @jeysinghanbu,

I think your problem is gradle. Please follow these steps:

1. `git clean -fdx`
2. `npm install`
3. Open Android Studio, update Android Studio and plugins.
4. Click to `Run App`

If you still getting error. look at this [issue](https://stackoverflow.com/questions/55790995/could-not-resolve-all-files-for-configuration-app-internal-aapt2-binary)

**Comment by jeysinghanbu** [comment]
I newly cloned the repo and did all the instruction as it is in repo description. It is working now. but there was an issue with image. I commented the code which has image component. Now it is working in both ios and android.

<img width="833" alt="Screenshot 2020-08-04 at 23 35 15" src="https://user-images.githubusercontent.com/4211519/89414723-81971200-d748-11ea-8626-46f96eca097d.png">
