### ISSUE TITLE
Release APKs crashes immediately at launch

### ISSUE THREAD

**Issue by dungtran3864** [keremcubuk/react-native-boilerplate#31]
Hi,

I recently cloned this boilerplate to build a React Native app. After successfully testing debug APKs on Android simulators, I moved on to build a release APK ready for production (following the instructions stated in the React Native documentation). From the project root directory in the terminal, I performed:

cd android
./gradlew bundleRelease

then I tried to run the release APK on an Android simulator with:

react-native run-android --variant=release

The build was successful, but immediately when the app launched, it crashed immediately. I tried to look at several GitHub and StackOverflow troubleshooting but I had no lucks. After a while, I started to think about what if the problem actually existed in the boilerplate itself. Hence, I cloned the boilerplate once again and built a release APK without any touching. I ran the release APK afterward on an Android simulator, and I surprisingly found that the app crashed immediately at launch as well. So now, I'm very certain that there is something wrong with the boilerplate that caused this issue.

**Steps to reproduce:**
- Clone the boilerplate. Follow the React Native documentation to build a release APK to upload to Google Play Store. Run the release APK on an Android simulator

**Error:**
- The app crashed immediately at launch.

**Expected result:**
- The app runs successfully.

**Comment by keremcubuk** [comment]
Hi @dungtran3864,

Thank you for using react-native-boilerplate. I will investigate the crash issue. Can you share the logs via Android Studio Logcat

**Comment by keremcubuk** [comment]
Hello again @dungtran3864,

I tried build with different simulators. I cannot reproduce the problem. Can you follow these steps and share the logs.

1.  `git clone https://github.com/keremcubuk/react-native-boilerplate.git`
2. `npm install`
3. Sync Gradle packages
4. `react-native run-android --variant=release`

If you have a problem with rename, check this project. https://github.com/junedomingo/react-native-rename

And give me more information. :)

**Comment by dungtran3864** [comment]
> Hi @dungtran3864,
> 
> Thank you for using react-native-boilerplate. I will investigate the crash issue. Can you share the logs via Android Studio Logcat

<img width="864" alt="Screen Shot 2020-08-05 at 10 23 51 AM" src="https://user-images.githubusercontent.com/26877974/89424504-de250d80-d705-11ea-92c6-48ea0b14b68b.png">

Here is the logcat of my app. I follow this instruction on React Native documentation to build a bundle release: https://reactnative.dev/docs/signed-apk-android. Then I run react-native run-android --variant=release.

Hope it helps you.

**Comment by dungtran3864** [comment]
> Hello again @dungtran3864,
> 
> I tried build with different simulators. I cannot reproduce the problem. Can you follow these steps and share the logs.
> 
> 1. `git clone https://github.com/keremcubuk/react-native-boilerplate.git`
> 2. `npm install`
> 3. Sync Gradle packages
> 4. `react-native run-android --variant=release`
> 
> If you have a problem with rename, check this project. https://github.com/junedomingo/react-native-rename
> 
> And give me more information. :)

Hi @keremcubuk,

I have tried to follow the steps you show above and the app is still crashing with its release APKs. I have simply cloned your boilerplate, built a release APK, and run the app on Android Simulator: Pixel 3 API 28. I have provided you a picture of the logs telling the reasons for the crash.

Picture of logcat showing the app crash:
<img width="895" alt="Screen Shot 2020-08-10 at 1 09 38 PM" src="https://user-images.githubusercontent.com/26877974/89810706-7c044800-db0b-11ea-9b86-c0f0874d50c2.png">

**Comment by keremcubuk** [comment]
Hello @dungtran3864,

I think this is Hermes problem. Did you activate Hermes?

https://hermesengine.dev/

In react-native 62.2, you have to use this version. https://github.com/facebook/hermes/releases/tag/v0.4.1

I will try it on my computer and I can release new package

**Comment by dungtran3864** [comment]
Hi @keremcubuk,

I have tried to switch on Hermes like you told, by switching "enableHermes" to true. However, the release APK still crashes. I have captured a screenshot of the new logcat for you.

<img width="958" alt="Screen Shot 2020-08-10 at 8 42 56 PM" src="https://user-images.githubusercontent.com/26877974/89844671-492d7480-db4a-11ea-83e7-8b01e195257c.png">

**Comment by dungtran3864** [comment]
Hello @keremcubuk 

I have fixed the release APK of my app to not crash while running on the Android simulator now. The issue is that the entryFile in build.gradle inside android/app is set to the wrong JS file, which is supposed to be index.js. Hence, I edit the entryFile to be index.js. I also update the buildToolsVersion in gradle.properties to be 29.0.2, as well as compileSdkVersion to be 29 and targetSdkVersion to be 29. Eventually, the release APK does not crash on startup anymore.

Note: this is done on my app, not on a purely cloned boilerplate.

Thank you for supporting me still!

**Comment by keremcubuk** [comment]
Hello @dungtran3864,

Can you open a pull request with the new new branch? I want to investigate and if is it OK, I will merge to project
