### ISSUE TITLE
[Question] Sample project with your boilerplate

### ISSUE THREAD

**Issue by jchiu0710** [keremcubuk/react-native-boilerplate#32]
Can you point me out to any simple but in production project which was developed using your boilerplate?  I need some coding reference for me to kick-start.

Thank you.

**Comment by keremcubuk** [comment]
Hello @jchiu0710,

I am working on two projects with this template but they are not in production yet. In a month, we are planning to share this app on project and I will add to references of boilerplate. May be someone who use this boilerplate, release their app on store.

Thank you for question and choose react-native-boilerplate
